services:
# chown vomlume bind mode 
  init-chown-volumes:
    image: busybox
    command: ["sh", "-c", "chown -R ${UID:-0}:${GID:-0} /app/log"]
    volumes:
      - ./log:/app/log/
    user: root
    env_file:
      - .env
    init: true
# service app
  mc-data-manger:
    depends_on:
      - init-chown-volumes
    build:
      context: .
      dockerfile: Dockerfile  
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
        USER: ${USER_NAME:-root}
        GROUP: ${GROUP_NAME:-root}
        WEB_DIR : ${WEB_DIR:-/web}
        APP_HOME: /app
    tty: true
    ports:
      - "3300:3300"
    restart : always
    volumes:
      - ./log:/app/log/
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

##################
##   OPTIONAL   ##
##################
    ## OPTIONAL LOGGING SETTINGS
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "5m"      # max-size each log file
    #     max-file: "10"      # max-index, log files

    ## OPTIONAL RESOURCE LIMITS
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.50"      # Capacity CPU : 0.5 (50% of a single CPU core)
    #       memory: "512M"    # Capacity Mem : 512MB
    #     reservations:
    #       cpus: "0.25"      # allocated CPU: 0.25 (25% of a single CPU core)
    #       memory: "256M"    # allocated Mem: 256MB