services:
# chown vomlume bind mode 
  init-chown-volumes:
    image: busybox
    command: ["sh", "-c", "chown -R ${UID:-0}:${GID:-0} /app/data/var"]
    volumes:
      - ./data:/app/data/
    user: root
    env_file:
      - .env
    init: true
# service app
  mc-data-manager:
    container_name: mc-data-manager
    depends_on:
      init-chown-volumes:
        condition: service_completed_successfully
      mc-data-manager-db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile  
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
        USER: ${USER_NAME:-root}
        GROUP: ${GROUP_NAME:-root}
        WEB_DIR : ${WEB_DIR:-/web}
        APP_HOME: /app
    tty: true
    ports:
      - "3300:3300"
    restart : always
    volumes:
      - ./data:/app/data/ # container-volume
      - ./scripts:/app/scripts/ # container-volume
      - /etc/localtime:/etc/localtime:ro # timezone
    env_file:
      - .env
    # Health check configuration
    # OK [ 2xx ,3xx}, ERR [4xx,5xx,...etc]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3300/readyZ"]
      interval: 30s
      timeout: 10s
      retries: 3
  mc-data-manager-db:
    image: mariadb:latest
    container_name: mc-data-manager-db
    command:
      - --skip-character-set-client-handshake
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - target: 3306
        published: 3301
        protocol: tcp
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - MYSQL_DATABASE=mcmp
      - MYSQL_USER=mcmp
      - MYSQL_PASSWORD=mcmp
      - MYSQL_ROOT_PASSWORD=mcmp


##################
##   OPTIONAL   ##
##################
    ## OPTIONAL LOGGING SETTINGS
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "5m"      # max-size each log file
    #     max-file: "10"      # max-index, log files

    ## OPTIONAL RESOURCE LIMITS
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2.0"      # Capacity CPU : 2.0 (100% of a Dual CPU core)
    #       memory: "1024M"    # Capacity Mem : 1024MB
    #     reservations:
    #       cpus: "0.5"      # allocated CPU: 0.25 (25% of a single CPU core)
    #       memory: "512M"    # allocated Mem: 256MB
