// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://cloud-barista.github.io",
            "email": "contact-to-cloud-barista@googlegroups.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/generate/aws": {
            "post": {
                "description": "Generate test data on AWS S3.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Test Data Generation]",
                    "[Object Storage]"
                ],
                "summary": "Generate test data on AWS S3",
                "parameters": [
                    {
                        "description": "Parameters required to generate test data",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.GenarateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully generated test data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/generate/dynamodb": {
            "post": {
                "description": "Generate test data on AWS DynamoDB.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Test Data Generation]",
                    "[NRDBMS]"
                ],
                "summary": "Generate test data on AWS DynamoDB",
                "parameters": [
                    {
                        "description": "Parameters required to generate test data",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.GenarateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully generated test data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/generate/firestore": {
            "post": {
                "description": "Generate test data on GCP Firestore.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Test Data Generation]",
                    "[NRDBMS]"
                ],
                "summary": "Generate test data on GCP Firestore",
                "parameters": [
                    {
                        "description": "Parameters required to generate test data",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.GenarateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully generated test data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/generate/gcp": {
            "post": {
                "description": "Generate test data on GCP Cloud Storage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Test Data Generation]",
                    "[Object Storage]"
                ],
                "summary": "Generate test data on GCP Cloud Storage",
                "parameters": [
                    {
                        "description": "Parameters required to generate test data",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.GenarateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully generated test data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/generate/linux": {
            "post": {
                "description": "Generate test data on on-premise Linux.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Test Data Generation]"
                ],
                "summary": "Generate test data on on-premise Linux",
                "parameters": [
                    {
                        "description": "Parameters required to generate test data",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.GenarateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully generated test data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/generate/mongodb": {
            "post": {
                "description": "Generate test data on NCP MongoDB.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Test Data Generation]",
                    "[NRDBMS]"
                ],
                "summary": "Generate test data on NCP MongoDB",
                "parameters": [
                    {
                        "description": "Parameters required to generate test data",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.GenarateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully generated test data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/generate/mysql": {
            "post": {
                "description": "Generate test data on MySQL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Test Data Generation]",
                    "[RDBMS]"
                ],
                "summary": "Generate test data on MySQL",
                "parameters": [
                    {
                        "description": "Parameters required to generate test data",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.GenarateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully generated test data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/generate/ncp": {
            "post": {
                "description": "Generate test data on NCP Object Storage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Test Data Generation]",
                    "[Object Storage]"
                ],
                "summary": "Generate test data on NCP Object Storage",
                "parameters": [
                    {
                        "description": "Parameters required to generate test data",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.GenarateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully generated test data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/generate/windows": {
            "post": {
                "description": "Generate test data on on-premise Windows.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Test Data Generation]"
                ],
                "summary": "Generate test data on on-premise Windows",
                "parameters": [
                    {
                        "description": "Parameters required to generate test data",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.GenarateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully generated test data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/aws/gcp": {
            "post": {
                "description": "Migrate data stored in AWS S3 to Google Cloud Storage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]",
                    "[Object Storage]"
                ],
                "summary": "Migrate data from AWS S3 to GCP",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/aws/linux": {
            "post": {
                "description": "Migrate data stored in AWS S3 to a Linux-based system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]"
                ],
                "summary": "Migrate data from AWS S3 to Linux",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/aws/ncp": {
            "post": {
                "description": "Migrate data stored in AWS S3 to Naver Cloud Object Storage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]",
                    "[Object Storage]"
                ],
                "summary": "Migrate data from AWS S3 to NCP",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/aws/windows": {
            "post": {
                "description": "Migrate data stored in AWS S3 to a Windows-based system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]"
                ],
                "summary": "Migrate data from AWS S3 to Windows",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/dynamodb/firestore": {
            "post": {
                "description": "Migrate data stored in AWS DynamoDB to Google Cloud Firestore.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]",
                    "[NRDBMS]"
                ],
                "summary": "Migrate data from DynamoDB to Firestore",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/dynamodb/mongodb": {
            "post": {
                "description": "Migrate data stored in AWS DynamoDB to Naver Cloud MongoDB.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]",
                    "[NRDBMS]"
                ],
                "summary": "Migrate data from DynamoDB to MongoDB",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/firestore/dynamodb": {
            "post": {
                "description": "Migrate data stored in Google Cloud Firestore to AWS DynamoDB.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]",
                    "[NRDBMS]"
                ],
                "summary": "Migrate data from Firestore to DynamoDB",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/firestore/mongodb": {
            "post": {
                "description": "Migrate data stored in Google Cloud Firestore to Naver Cloud MongoDB.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]",
                    "[NRDBMS]"
                ],
                "summary": "Migrate data from Firestore to MongoDB",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/gcp/aws": {
            "post": {
                "description": "Migrate data stored in GCP Cloud Storage to AWS S3.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]",
                    "[Object Storage]"
                ],
                "summary": "Migrate data from GCP to AWS S3",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/gcp/linux": {
            "post": {
                "description": "Migrate data stored in GCP Cloud Storage to a Linux-based system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]"
                ],
                "summary": "Migrate data from GCP to Linux",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/gcp/ncp": {
            "post": {
                "description": "Migrate data stored in GCP Cloud Storage to NCP Object Storage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]",
                    "[Object Storage]"
                ],
                "summary": "Migrate data from GCP to NCP Object Storage",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/gcp/windows": {
            "post": {
                "description": "Migrate data stored in GCP Cloud Storage to a Windows-based system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]"
                ],
                "summary": "Migrate data from GCP to Windows",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/linux/aws": {
            "post": {
                "description": "Migrate data stored in a Linux-based system to AWS S3.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]"
                ],
                "summary": "Migrate data from Linux to AWS S3",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/linux/gcp": {
            "post": {
                "description": "Migrate data stored in a Linux-based system to GCP Cloud Storage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]"
                ],
                "summary": "Migrate data from Linux to GCP Cloud Storage",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/linux/ncp": {
            "post": {
                "description": "Migrate data stored in a Linux-based system to NCP Object Storage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]"
                ],
                "summary": "Migrate data from Linux to NCP Object Storage",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/mongodb/dynamodb": {
            "post": {
                "description": "Migrate data stored in Naver Cloud MongoDB to AWS DynamoDB.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]",
                    "[NRDBMS]"
                ],
                "summary": "Migrate data from MongoDB to DynamoDB",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/mongodb/firestore": {
            "post": {
                "description": "Migrate data stored in Naver Cloud MongoDB to Google Cloud Firestore.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]",
                    "[NRDBMS]"
                ],
                "summary": "Migrate data from MongoDB to Firestore",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/mysql": {
            "post": {
                "description": "Migrate data from one MySQL database to another MySQL database.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]",
                    "[RDBMS]"
                ],
                "summary": "Migrate data from MySQL to MySQL",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/ncp/aws": {
            "post": {
                "description": "Migrate data stored in NCP Object Storage to AWS S3.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]",
                    "[Object Storage]"
                ],
                "summary": "Migrate data from NCP to AWS S3",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/ncp/gcp": {
            "post": {
                "description": "Migrate data stored in NCP Object Storage to GCP Cloud Storage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]",
                    "[Object Storage]"
                ],
                "summary": "Migrate data from NCP to GCP Cloud Storage",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    },
                    {
                        "type": "file",
                        "description": "Parameters required to generate test data",
                        "name": "gcpCredential",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/ncp/linux": {
            "post": {
                "description": "Migrate data stored in NCP Object Storage to a Linux-based system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]"
                ],
                "summary": "Migrate data from NCP to Linux",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/ncp/windows": {
            "post": {
                "description": "Migrate data stored in NCP Object Storage to a Windows-based system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]"
                ],
                "summary": "Migrate data from NCP to Windows",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/windows/aws": {
            "post": {
                "description": "Migrate data stored in a Windows-based system to AWS S3.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]"
                ],
                "summary": "Migrate data from Windows to AWS S3",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/windows/gcp": {
            "post": {
                "description": "Migrate data stored in a Windows-based system to GCP Cloud Storage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]"
                ],
                "summary": "Migrate data from Windows to GCP Cloud Storage",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        },
        "/migration/windows/ncp": {
            "post": {
                "description": "Migrate data stored in a Windows-based system to NCP Object Storage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Data Migration]"
                ],
                "summary": "Migrate data from Windows to NCP Object Storage",
                "parameters": [
                    {
                        "description": "Parameters required for migration",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MigrateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully migrated data",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BasicResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.GenarateTask": {
            "type": "object",
            "properties": {
                "operationId": {
                    "type": "string"
                },
                "targetPoint": {
                    "$ref": "#/definitions/models.GenTaskTarget"
                }
            }
        },
        "controllers.MigrateTask": {
            "type": "object",
            "properties": {
                "operationId": {
                    "type": "string"
                },
                "sourcePoint": {
                    "$ref": "#/definitions/models.ProviderConfig"
                },
                "targetPoint": {
                    "$ref": "#/definitions/models.ProviderConfig"
                }
            }
        },
        "models.BasicResponse": {
            "type": "object",
            "properties": {
                "Error": {
                    "type": "string"
                },
                "Result": {
                    "type": "string"
                }
            }
        },
        "models.GenTaskTarget": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "checkCSV": {
                    "type": "boolean"
                },
                "checkGIF": {
                    "type": "boolean"
                },
                "checkJSON": {
                    "type": "boolean"
                },
                "checkPNG": {
                    "type": "boolean"
                },
                "checkSQL": {
                    "type": "boolean"
                },
                "checkServerJSON": {
                    "type": "boolean"
                },
                "checkServerSQL": {
                    "type": "boolean"
                },
                "checkTXT": {
                    "type": "boolean"
                },
                "checkXML": {
                    "type": "boolean"
                },
                "checkZIP": {
                    "type": "boolean"
                },
                "databaseId": {
                    "type": "string"
                },
                "databaseName": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "profileName": {
                    "type": "string"
                },
                "projectId": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "sizeCSV": {
                    "type": "string"
                },
                "sizeGIF": {
                    "type": "string"
                },
                "sizeJSON": {
                    "type": "string"
                },
                "sizePNG": {
                    "type": "string"
                },
                "sizeSQL": {
                    "type": "string"
                },
                "sizeServerJSON": {
                    "type": "string"
                },
                "sizeServerSQL": {
                    "type": "string"
                },
                "sizeTXT": {
                    "type": "string"
                },
                "sizeXML": {
                    "type": "string"
                },
                "sizeZIP": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.ProviderConfig": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "databaseId": {
                    "type": "string"
                },
                "databaseName": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "profileName": {
                    "type": "string"
                },
                "projectId": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "latest",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MC-Data-Manager REST API",
	Description:      "MC-Data-Manager REST API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
